# Generated by Django 3.0 on 2020-12-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201203_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='payment_option',
            field=models.CharField(default='P', max_length=2),
            preserve_default=False,
        ),
    ]
