# Generated by Django 3.0 on 2020-11-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201108_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_slug',
            field=models.SlugField(default='product-item'),
            preserve_default=False,
        ),
    ]
