# Generated by Django 3.0 on 2020-12-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_billingaddress_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'PayPal'), ('PS', 'PayStack')], max_length=2),
        ),
    ]
